# Generated by Django 5.1.7 on 2025-10-09 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaluser_business_key_user_business_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='business_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_key',
        ),
    ]
