# Generated by Django 5.1.7 on 2025-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_historicaluser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='date_joined',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
