# Generated by Django 5.2.10 on 2026-06-03 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='recipient_email',
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
