# Generated by Django 5.2.10 on 2026-06-04 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_invitation_recipient_email_invitation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 5, 16, 55, 15, 972379, tzinfo=datetime.timezone.utc)),
        ),
    ]
