# Generated by Django 5.2.10 on 2026-06-19 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_headquarters_unique_together_and_more'),
        ('users', '0012_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 20, 16, 23, 6, 884978, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('user', 'business')},
        ),
    ]
