# Generated by Django 5.2.10 on 2026-06-27 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_invitation_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 28, 3, 29, 28, 827458, tzinfo=datetime.timezone.utc)),
        ),
    ]
