# Generated by Django 5.2.10 on 2026-07-17 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 18, 1, 44, 47, 518711, tzinfo=datetime.timezone.utc)),
        ),
    ]
