# Generated by Django 5.1.7 on 2025-03-14 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSegregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=255)),
                ('family_model', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('op_capability', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_energy_type', models.CharField(max_length=100)),
                ('technical_data', models.TextField()),
                ('additional_info', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('system_segregation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.systemsegregation')),
            ],
        ),
    ]
