# Generated by Django 5.1.7 on 2025-04-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_business_historicalbusiness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.AlterField(
            model_name='asset',
            name='fuel_energy_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='system_segregation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.systemsegregation'),
        ),
        migrations.DeleteModel(
            name='HistoricalBusiness',
        ),
    ]
