# Generated by Django 5.1.7 on 2025-08-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_delete_business_alter_asset_fuel_energy_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsegregation',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
