# Generated by Django 5.1.7 on 2025-09-25 02:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_alter_systemsegregation_description'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermissionType', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1, verbose_name=[(1, 'manage_users'), (2, 'manage_locations'), (3, 'manage_assets')]), size=None)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1, verbose_name=[(1, 'view'), (2, 'add'), (3, 'change'), (4, 'delete')]), size=None)),
                ('asset_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('location_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.business')),
            ],
        ),
    ]
