# Generated by Django 5.1.7 on 2025-09-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpermission',
            old_name='PermissionType',
            new_name='permission_type',
        ),
    ]
