# Generated by Django 5.1.7 on 2025-09-28 22:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_rename_permissiontype_adminpermission_permission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpermission',
            name='permission_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=2, verbose_name=[(1, 'create_users'), (2, 'read_users'), (3, 'update_users'), (4, 'delete_users'), (5, 'create_businesses'), (6, 'read_businesses'), (7, 'update_businesses'), (8, 'delete_businesses'), (9, 'create_headquarters'), (10, 'read_headquarters'), (11, 'update_headquarters'), (12, 'delete_headquarters')]), size=None),
        ),
    ]
