# Generated by Django 5.1.7 on 2025-10-09 02:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_userbusinessmember'),
        ('permissions', '0004_alter_adminpermission_user_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpermission',
            name='permission_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=2, verbose_name=[(1, 'create_users'), (2, 'read_users'), (3, 'update_users'), (4, 'delete_users'), (5, 'create_businesses'), (6, 'read_businesses'), (7, 'update_businesses'), (8, 'delete_businesses'), (9, 'create_headquarters'), (10, 'read_headquarters'), (11, 'update_headquarters'), (12, 'delete_headquarters'), (13, 'create_assets'), (14, 'read_assets'), (15, 'update_assets'), (16, 'delete_assets'), (17, 'create_components'), (18, 'read_components'), (19, 'update_components'), (20, 'delete_components')]), size=None),
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='user_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BusinessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_business', to='locations.business')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=6, verbose_name=[6, 10, 14, 13, 18]), size=None)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LocationPermission',
        ),
    ]
