# Generated by Django 5.1.7 on 2025-10-12 03:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_alter_adminpermission_permission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpermission',
            name='permission_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=2, verbose_name=[(1, 'create_user'), (2, 'read_user'), (3, 'update_user'), (4, 'delete_user'), (5, 'create_business'), (6, 'read_business'), (7, 'update_business'), (8, 'delete_business'), (9, 'create_headquarter'), (10, 'read_headquarter'), (11, 'update_headquarter'), (12, 'delete_headquarter'), (13, 'create_asset'), (14, 'read_asset'), (15, 'update_asset'), (16, 'delete_asset'), (17, 'create_component'), (18, 'read_component'), (19, 'update_component'), (20, 'delete_component')]), size=None),
        ),
    ]
