# Generated by Django 5.1.7 on 2025-11-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('permissions', '0006_alter_adminpermission_permission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerpermission',
            name='user_key',
        ),
        migrations.CreateModel(
            name='ForbiddenGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forbidden_permissions', to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'unique_together': {('group', 'permission')},
            },
        ),
        migrations.DeleteModel(
            name='AdminPermission',
        ),
        migrations.DeleteModel(
            name='ManagerPermission',
        ),
    ]
