# Generated by Django 5.1.7 on 2025-12-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_groupbusinesspermission_userbusinesspermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbusinesspermission',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userbusinesspermission',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
