# Generated by Django 5.1.7 on 2025-12-10 19:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0003_alter_business_name_alter_business_tin_and_more'),
        ('permissions', '0009_groupbusinesspermission_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupbusinesspermission',
            unique_together={('group_key', 'business_key', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='userbusinesspermission',
            unique_together={('user_key', 'business_key', 'permission')},
        ),
    ]
