# Generated by Django 5.1.7 on 2025-12-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0003_alter_business_name_alter_business_tin_and_more'),
        ('permissions', '0010_alter_groupbusinesspermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupbusinesspermission',
            unique_together={('group_key', 'business_key')},
        ),
        migrations.RemoveField(
            model_name='groupbusinesspermission',
            name='permission',
        ),
    ]
