# Generated by Django 5.1.7 on 2025-12-30 20:10

from django.db import migrations

from django.apps import apps

default_app_labels = ['admin', 'auth','content_types','sessions']
default_content_types = {
      'systemsegregation', 
      'asset', 
      'maintenanceroutine', 
      'routinestep', 
      'assetsystem', 
      'subsystemcomponent', 
      'minimumcomponent', 
      'business',
      'headquarters', 
      'internallocation', 
      'userbusinessmember'     
}
default_actions = {
      'add','change','delete','view'
}


def getAllAppsmodels():
      models = apps.get_models()

      return [(model._meta.app_label, model.__name__) for model in models]



forbidden_permissions = {
      
      #'OPERATOR': {
      #      'app_labels':['users', 'permissions']+default_app_labels,
      #      'content_types':{
      #              'systemsegregation':{ 'add','change','delete' }, 
      #              'asset':{ 'add','change','delete' }, 
      #              'maintenanceroutine':{ 'add','change','delete' }, 
      #              'routinestep':{ 'add','change','delete' }, 
      #              'assetsystem':{ 'add','change','delete' }, 
      #              'subsystemcomponent':{ 'add','change','delete' }, 
      #              'minimumcomponent':{ 'add','change','delete' }, 
      #              'business':{ 'add','change','delete' }, 
      #              'headquarters':{ 'add','change','delete' }, 
      #              'internallocation':{ 'add','change','delete' }, 
      #              'userbusinessmember':{ 'add','change','delete' }, 
      #      }
      #  },

      'MANAGER': {
            'app_labels':['permissions']+default_app_labels,
            'content_types':{
                    'systemsegregation':{ }, 
                    'asset':{ }, 
                    'maintenanceroutine':{ }, 
                    'routinestep':{ }, 
                    'assetsystem':{ }, 
                    'subsystemcomponent':{ }, 
                    'minimumcomponent':{ }, 
                    'business':{ 'add','change','delete' },
                    'headquarters':{ 'add','change','delete' }, 
                    'internallocation':{ }, 
                    'userbusinessmember':{ }
            }
      },

      'ADMIN': {
            'app_labels':default_app_labels,
            'content_types':{
                    'systemsegregation':{ }, 
                    'asset':{ }, 
                    'maintenanceroutine':{ }, 
                    'routinestep':{ }, 
                    'assetsystem':{ }, 
                    'subsystemcomponent':{ }, 
                    'minimumcomponent':{ }, 
                    'business':{ 'add','change','delete' }, 
                    'headquarters':{ }, 
                    'internallocation':{ }, 
                    'userbusinessmember':{ },
                    'user':{ }, 
                    'historicaluser':{ }, 
            }
      }


}


def resetForbiddenPermissions(apps, schema_Editor):
      fgpermission = apps.get_model('permissions', 'ForbiddenGroupPermissions')
      fgpermission.objects.all().delete()



def defaultGroupsPermissionsProhibitions(apps, schema_editor):
        #update_or_create, if the volume is big, use bulk_create, both model functions
        fgpermission = apps.get_model('permissions', 'ForbiddenGroupPermissions')
        contenttypes = apps.get_model('contenttypes', 'ContentType')
        Group = apps.get_model('auth', 'Group')
        Permission = apps.get_model('auth','Permission')


        for gname, data in forbidden_permissions.items():
            for app_label in data['app_labels']:
                conttypes = contenttypes.objects.filter(app_label = app_label)
                nombres_modelos = [cont.model for cont in conttypes]

                for modelo in nombres_modelos:
                        for action in default_actions:
                            
                            try:
                                grupo = Group.objects.get(name=gname)
                                permiso = Permission.objects.get(codename = action+"_"+modelo)
                                fgpermission.objects.update_or_create(group=grupo, permission=permiso) #obj, created = 
                            except:
                                    #print(f"Failed creation of prohibition {action+"_"+modelo} for group {gname} (app_labels)")
                                    continue
                
            for key, modelo in data['content_types'].items():
                  if not modelo:
                        continue
                  
                  for action in modelo:
                        try:
                            grupo = Group.objects.get(name=gname)
                            permiso = Permission.objects.get(codename = action+"_"+key)
                            fgpermission.objects.update_or_create(group=grupo, permission=permiso)
                        except:
                            #print(f"Failed creation of prohibition {action+"_"+key} for group {gname} (content_types)")
                            continue
                        
                
                  

                    











class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0013_alter_groupbusinesspermission_user_key'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(defaultGroupsPermissionsProhibitions,resetForbiddenPermissions)
    ]
