# Generated by Django 5.2.10 on 2026-06-01 22:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.apps import apps







class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0004_alter_headquarters_unique_together_and_more'),
        ('permissions', '0014_create_default_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupbusinesspermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupbusinesspermission',
            name='business_key',
        ),
        migrations.RemoveField(
            model_name='groupbusinesspermission',
            name='group_key',
        ),
        migrations.RemoveField(
            model_name='groupbusinesspermission',
            name='user_key',
        ),
        migrations.AddField(
            model_name='userbusinesspermission',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userbusinesspermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userbusinesspermission',
            name='membership',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='permissions.businessmembership'),
        ),
        migrations.AlterUniqueTogether(
            name='userbusinesspermission',
            unique_together={('membership', 'permission')},
        ),
        migrations.CreateModel(
            name='BusinessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('business', 'Business')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_system', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.business')),
                ('permissions', models.ManyToManyField(to='auth.permission')),
            ],
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permissions.businessrole'),
        ),
        migrations.DeleteModel(
            name='ForbiddenGroupPermissions',
        ),
        migrations.DeleteModel(
            name='GroupBusinessPermission',
        ),
        migrations.RemoveField(
            model_name='userbusinesspermission',
            name='active',
        ),
        migrations.RemoveField(
            model_name='userbusinesspermission',
            name='business_key',
        ),
        migrations.RemoveField(
            model_name='userbusinesspermission',
            name='user_key',
        ),
        migrations.AddConstraint(
            model_name='businessrole',
            constraint=models.UniqueConstraint(fields=('name', 'business'), name='unique_role_name'),
        ),
        migrations.AddConstraint(
            model_name='businessrole',
            constraint=models.UniqueConstraint(fields=('business', 'level'), name='unique_business_level'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmembership',
            unique_together={('user', 'business')},
        ),
    ]
