# Generated by Django 5.2.10 on 2026-06-04 16:57

from django.db import migrations


default_global_roles = {
  'Owner' : 100,
  'Administrator' : 70,
  'Manager' : 50,
  'Worker' : 10
}


def createGlobalBusinessRoles(apps, schema_editor):
    BusinessRole = apps.get_model('permissions','BusinessRole')
    for role in default_global_roles.keys():
      role_is = BusinessRole.objects.filter(scope='global',name = role, level=default_global_roles[role]).first()
      
      if not role_is:
        BusinessRole.objects.create(
          scope='global',
          business=None, 
          name=role,
          is_system=True, 
          level=default_global_roles[role])
    
    
def deleteAllRoles(apps, schema_editor):
  BusinessRole = apps.get_model('permissions','BusinessRole')
  BusinessRole.objects.all().delete()




class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0015_alter_groupbusinesspermission_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(createGlobalBusinessRoles,deleteAllRoles),
    ]
