# Generated by Django 5.2.10 on 2026-06-27 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0016_auto_20260604_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbusinesspermission',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.businessmembership'),
        ),
    ]
