# Generated by Django 5.1.7 on 2025-03-14 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tin', models.CharField(max_length=255)),
                ('utr', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('business_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.business')),
            ],
        ),
        migrations.CreateModel(
            name='InternalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('headquarters_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.headquarters')),
            ],
        ),
    ]
