# Generated by Django 5.1.7 on 2025-12-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_userbusinessmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='tin',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='utr',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
