# Generated by Django 5.2.10 on 2026-03-19 20:51

from django.db import migrations



def reset_duplicates(apps, schema_editor):
    Headquarters = apps.get_model('locations', 'headquarters')
    for obj in Headquarters.objects.all():
        obj.name = obj.name.split("_dup")[0]
        obj.save()


def fix_duplicates(apps, schema_editor):
    Headquarters = apps.get_model('locations', 'headquarters')
    
    seen = {}
    for obj in Headquarters.objects.all():
        
        checked = obj.name + '_' + str(obj.business_key.id)

        if not checked in seen.keys():
            seen[checked] = 0
        else:
            if seen[checked]>=0:
                seen[checked]+=1
                obj.name = f"{obj.name}_dup_{seen[checked]}"
                obj.save()




class Migration(migrations.Migration):
    
    dependencies = [
        ('locations', '0003_alter_business_name_alter_business_tin_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_duplicates,reset_duplicates),
        migrations.AlterUniqueTogether(
            name='headquarters',
            unique_together={('business_key', 'name')},
        ),
        migrations.DeleteModel(
            name='UserBusinessMember',
        ),
    ]
